---
- name: Setup MySQL Server
  hosts: mysql_server
  become: yes
  roles:
    - mysql

- name: Setup Maven Build Server
  hosts: maven_server
  become: yes
  roles:
    - maven

- name: Setup Tomcat Server
  hosts: tomcat_server
  become: yes
  roles:
    - tomcat
