---
- name: Install Java 17 and Maven on Ubuntu
  hosts: all
  become: true
  tasks:

    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - curl
        - gnupg
        - software-properties-common

    - name: Add OpenJDK 17 repository (for older Ubuntu versions)
      apt_repository:
        repo: ppa:openjdk-r/ppa
        state: present
      when: ansible_distribution_release != "jammy"

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Set JAVA_HOME environment variable
      copy:
        dest: /etc/profile.d/java.sh
        content: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
      mode: 0644

    - name: Ensure JAVA_HOME is loaded
      shell: source /etc/profile.d/java.sh
      args:
        executable: /bin/bash

    - name: Download Maven binary
      get_url:
        url: https://downloads.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
        dest: /tmp/apache-maven.tar.gz

    - name: Extract Maven
      unarchive:
        src: /tmp/apache-maven.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Create symlink for Maven
      file:
        src: /opt/apache-maven-3.9.6
        dest: /opt/maven
        state: link

    - name: Set MAVEN_HOME environment variable
      copy:
        dest: /etc/profile.d/maven.sh
        content: |
          export MAVEN_HOME=/opt/maven
          export PATH=$MAVEN_HOME/bin:$PATH
      mode: 0644

    - name: Ensure MAVEN_HOME is loaded
      shell: source /etc/profile.d/maven.sh
      args:
        executable: /bin/bash
