---
- name: Install Java 17 and Maven (minimal)
  hosts: all
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java 17 and Maven
      apt:
        name:
          - openjdk-17-jdk
          - maven
        state: present
