---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Java and Maven
  apt:
    name:
      - openjdk-17-jdk
      - maven
    state: present

- name: Clone project
  git:
    repo: 'https://github.com/Lt-Hariom-2002/spring-petclinic-jenkins.git'
    dest: /home/ubuntu/app

- name: Build Jar file
  command: mvn package
  args:
    chdir: /home/ubuntu/app
